# permissions for end users to view cloudnlouds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cloudnloud-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cnl-operator
    app.kubernetes.io/part-of: cnl-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudnloud-viewer-role
rules:
- apiGroups:
  - api.cloudnloud.com
  resources:
  - cloudnlouds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.cloudnloud.com
  resources:
  - cloudnlouds/status
  verbs:
  - get
