---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - api.cloudnloud.com
  resources:
  - cloudnlouds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.cloudnloud.com
  resources:
  - cloudnlouds/finalizers
  verbs:
  - update
- apiGroups:
  - api.cloudnloud.com
  resources:
  - cloudnlouds/status
  verbs:
  - get
  - patch
  - update
